### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by NidhiPatel7499** [muhammadshiraz/YOLO-Real-Time-Object-Detection#3]
I downloaded all your files, including the cfg and weights files and ran the yolo_real_time_webcam and detector 1.py files, but its shows these errors.
Could you please help me fugure out where I am going wrong?

Traceback (most recent call last):
  File "real_time_yolo_webcam.py", line 10, in <module>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "real_time_yolo_webcam.py", line 10, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

Traceback (most recent call last):
  File "real_time_yolo_detector1.py", line 11, in <module>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "real_time_yolo_detector1.py", line 11, in <listcomp>
    output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]

**Comment by vijethx** [comment]
change 
`output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]` to 
`output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]`
